### ISSUE TITLE
[ERROR/2022-08-26 14:18:07,563] pyrogram.dispatcher: 'directLink'

### ISSUE THREAD

**Issue by 0xSaurabhx** [DinuthInduwara/OC.GoFile-Uploading-Telegram-Bot#1]
[ERROR/2022-08-26 14:18:07,563] pyrogram.dispatcher: 'directLink'
Traceback (most recent call last):
File "/opt/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
await handler.callback(self.client, *args)
File "main.py", line 51, in main
directlink = upload["data"]["directLink"]
KeyError: 'directLink

**Comment by 0xSaurabhx** [comment]
Just changed directlink = upload["data"]["directLink"] ---> directlink = upload["data"]["downloadPage"]

It worked!
